# Change these first
owner: lefuex # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Chez Daniel
    url: https://www.chez-daniel.com
  - name: Chor unterwegs
    url: https://www.chor-unterwegs.org
  - name: Eventbackend
    url: https://eventbackend.de
  - name: GSS Bruno
    url: https://www.gss-bruno.de
  - name: Hochzeitskribbeln
    url: https://www.hochzeitskribbeln.com
  - name: Janine Röber
    url: https://www.janine-roeber.de
  - name: Koblenz Tennis
    url: https://www.koblenz-tennis.de
  - name: Lefuex
    url: https://www.lefuex.de
  - name: Miss Evangeline
    url: https://www.miss-evangeline.de
  - name: Miss Evangeline Business
    url: https://business.miss-evangeline.de
  - name: Muthandel
    url: https://www.muthandel.de
  - name: Praxis Fehlerteufel
    url: https://www.praxis-fehlerteufel.de
  

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** uptime monitor"
  introMessage: Status page
  navbar:
    - title: Status
      href: /
    #- title: GitHub
    #  href: https://github.com/$OWNER/$REPO

notifications:
  - type: email

assignees:
  - lefuex

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
